import React, { useState, useEffect } from 'react';
import { Copy, Check, AlertCircle, RefreshCw } from 'lucide-react';
import { fetchCases } from '../api/cases';
import { fetchSarByCaseId } from '../api/sar';
import type { DynamicCase } from '../types/case';
import type { SarRecord } from '../types/sar';
import { Badge } from '../components/common/Badge';
import { Skeleton } from '../components/common/Skeleton';
import { ErrorState } from '../components/common/ErrorState';
import { formatCurrency, formatPattern } from '../utils/formatters';

export const SarReports: React.FC = () => {
  const [sarCases, setSarCases] = useState<DynamicCase[]>([]);
  const [selectedCaseId, setSelectedCaseId] = useState<string | null>(null);
  const [activeSar, setActiveSar] = useState<SarRecord | null>(null);
  const [isLoadingList, setIsLoadingList] = useState(true);
  const [isLoadingDetail, setIsLoadingDetail] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [copied, setCopied] = useState(false);

  const loadSarCases = async () => {
    setIsLoadingList(true);
    setError(null);
    try {
      const res = await fetchCases({ page: 1, page_size: 50 });
      // Cases where sar_required is true or sar_status is GENERATED
      const filtered = (res.items || []).filter(
        (c) => c.sar_required || c.sar_status === 'GENERATED' || c.verdict === 'fraud'
      );
      setSarCases(filtered);
      if (filtered.length > 0 && !selectedCaseId) {
        setSelectedCaseId(filtered[0].case_id);
      }
    } catch (err: any) {
      setError(err.message || 'Failed to load SAR cases list.');
    } finally {
      setIsLoadingList(false);
    }
  };

  useEffect(() => {
    loadSarCases();
  }, []);

  useEffect(() => {
    const loadSar = async () => {
      if (!selectedCaseId) return;
      setIsLoadingDetail(true);
      try {
        const sarData = await fetchSarByCaseId(selectedCaseId);
        setActiveSar(sarData);
      } catch (err) {
        console.error('Failed to load SAR for case', err);
        setActiveSar(null);
      } finally {
        setIsLoadingDetail(false);
      }
    };
    loadSar();
  }, [selectedCaseId]);

  const handleCopyNarrative = () => {
    if (!activeSar?.narrative) return;
    navigator.clipboard.writeText(activeSar.narrative);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="space-y-6 text-left">
      {/* Header */}
      <div className="flex flex-wrap items-center justify-between gap-4 border-b border-slate-200 pb-4">
        <div>
          <div className="flex items-center gap-2">
            <h1 className="text-xl font-bold tracking-tight text-slate-900">
              FinCEN Suspicious Activity Reports (SAR)
            </h1>
            <span className="text-[11px] font-mono px-2 py-0.5 rounded-full bg-rose-100 text-rose-800 font-semibold border border-rose-300">
              {sarCases.length} Filings Generated
            </span>
          </div>
          <p className="text-xs text-slate-500 mt-0.5">
            Automated FinCEN BSA filing artifacts generated by the agent for confirmed fraud investigations.
          </p>
        </div>

        <button
          onClick={loadSarCases}
          className="p-2 text-slate-500 hover:text-slate-800 bg-white border border-slate-200 rounded-md hover:bg-slate-50 shadow-sm transition-colors"
          title="Refresh List"
        >
          <RefreshCw className={`w-3.5 h-3.5 ${isLoadingList ? 'animate-spin' : ''}`} />
        </button>
      </div>

      {error ? (
        <ErrorState message={error} onRetry={loadSarCases} />
      ) : (
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
          {/* Left: SAR Cases Selector */}
          <div className="lg:col-span-4 space-y-3">
            <span className="text-[10px] font-bold text-slate-400 uppercase tracking-wider block">
              SAR Filing Artifacts
            </span>
            {isLoadingList ? (
              <Skeleton className="h-64 w-full rounded-lg" />
            ) : (
              <div className="space-y-2 max-h-[640px] overflow-y-auto custom-scrollbar pr-1">
                {sarCases.map((c) => {
                  const isSelected = selectedCaseId === c.case_id;
                  return (
                    <button
                      key={c.case_id}
                      onClick={() => setSelectedCaseId(c.case_id)}
                      className={`w-full p-3 rounded-lg border text-left transition-all ${
                        isSelected
                          ? 'bg-sky-50 border-sky-500 ring-1 ring-sky-500 shadow-sm'
                          : 'bg-white border-slate-200 hover:border-slate-300'
                      }`}
                    >
                      <div className="flex items-center justify-between mb-1">
                        <span className="font-mono font-bold text-sky-800 text-xs">{c.case_id}</span>
                        <Badge label={formatCurrency(c.exposure_usd)} variant="red" size="sm" />
                      </div>
                      <div className="text-[11px] font-medium text-slate-700 truncate">
                        {formatPattern(c.fraud_pattern)}
                      </div>
                      <div className="text-[10px] text-slate-500 mt-0.5">
                        Card: {c.card_id} &bull; Txn: #{c.flagged_txn_id}
                      </div>
                    </button>
                  );
                })}
              </div>
            )}
          </div>

          {/* Right: Selected SAR Viewer */}
          <div className="lg:col-span-8">
            {isLoadingDetail ? (
              <Skeleton className="h-96 w-full rounded-lg" />
            ) : activeSar ? (
              <div className="bg-white p-6 rounded-lg border border-slate-200 shadow-sm text-xs space-y-5">
                {/* Header Banner */}
                <div className="flex flex-wrap items-center justify-between gap-3 border-b border-slate-100 pb-4">
                  <div>
                    <div className="flex items-center gap-2">
                      <span className="text-sm font-bold text-slate-900">
                        FinCEN Form 111 / BSA SAR Draft
                      </span>
                      <Badge label="FILING REQUIRED" variant="red" size="sm" />
                    </div>
                    <span className="text-[11px] text-slate-500 block mt-0.5">
                      Case Reference: <strong className="font-mono text-slate-700">{activeSar.case_id}</strong>
                    </span>
                  </div>

                  <div className="flex items-center gap-2">
                    <button
                      onClick={handleCopyNarrative}
                      className="px-3 py-1.5 text-xs text-slate-700 border border-slate-200 rounded-md hover:bg-slate-50 transition-colors inline-flex items-center gap-1.5 shadow-sm"
                    >
                      {copied ? <Check className="w-3.5 h-3.5 text-emerald-600" /> : <Copy className="w-3.5 h-3.5" />}
                      <span>{copied ? 'Copied Narrative' : 'Copy Narrative'}</span>
                    </button>
                  </div>
                </div>

                {/* Primary Subject & Transaction Details */}
                <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 bg-slate-50 p-3 rounded-lg border border-slate-200 text-xs">
                  <div>
                    <span className="text-[10px] uppercase font-bold text-slate-400 block">Primary Subject</span>
                    <span className="font-mono text-slate-900 font-semibold">
                      {activeSar.primary_subject?.customer_id || activeSar.subjects?.[0]?.customer_id || 'N/A'}
                    </span>
                  </div>
                  <div>
                    <span className="text-[10px] uppercase font-bold text-slate-400 block">Instrument</span>
                    <span className="font-mono text-slate-900 font-semibold">
                      {activeSar.primary_subject?.card_id || activeSar.subjects?.[0]?.card_id || 'N/A'}
                    </span>
                  </div>
                  <div>
                    <span className="text-[10px] uppercase font-bold text-slate-400 block">Flagged Amount</span>
                    <span className="font-mono text-slate-900 font-semibold">
                      {formatCurrency(activeSar.total_exposure_usd || activeSar.total_amount_usd || 0)}
                    </span>
                  </div>
                  <div>
                    <span className="text-[10px] uppercase font-bold text-slate-400 block">Filing Typology</span>
                    <span className="text-slate-900 font-semibold capitalize">
                      {formatPattern(activeSar.reason || activeSar.trigger_reason || 'Card Fraud')}
                    </span>
                  </div>
                </div>

                {/* Narrative Section */}
                <div>
                  <span className="text-[11px] font-bold text-slate-700 uppercase tracking-wider block mb-2">
                    Part V: Suspicious Activity Information Narrative
                  </span>
                  <div className="p-4 bg-slate-900 text-slate-200 rounded-lg font-mono text-[11px] leading-relaxed border border-slate-800 whitespace-pre-wrap max-h-80 overflow-y-auto custom-scrollbar">
                    {activeSar.narrative || 'No narrative generated.'}
                  </div>
                </div>

                {/* Evidence References */}
                {activeSar.evidence_references && activeSar.evidence_references.length > 0 && (
                  <div>
                    <span className="text-[10px] font-bold text-slate-400 uppercase tracking-wider block mb-1">
                      Corroborating Graph Evidence References ({activeSar.evidence_references.length})
                    </span>
                    <div className="space-y-1">
                      {activeSar.evidence_references.map((ref: string, idx: number) => (
                        <div key={idx} className="p-2 bg-slate-50 border border-slate-200 rounded text-[11px] text-slate-700 flex items-start gap-1.5">
                          <span className="font-mono font-bold text-sky-700">[{idx + 1}]</span>
                          <span>{ref}</span>
                        </div>
                      ))}
                    </div>
                  </div>
                )}

                {/* Regulatory Disclaimer Notice */}
                <div className="p-3 bg-amber-50 border border-amber-200 rounded-lg text-[11px] text-amber-900 flex items-start gap-2">
                  <AlertCircle className="w-4 h-4 text-amber-700 shrink-0 mt-0.5" />
                  <div>
                    <strong className="block font-semibold">Regulatory Compliance Notice:</strong>
                    This SAR document is an autonomous pre-filing artifact formatted per FinCEN BSA guidance. This platform does not directly transmit e-filings to regulatory agencies. Human compliance review is required prior to external submission.
                  </div>
                </div>
              </div>
            ) : (
              <div className="p-16 text-center text-slate-400 text-xs bg-white rounded-lg border border-slate-200">
                Select a SAR case from the left list to review filing details.
              </div>
            )}
          </div>
        </div>
      )}
    </div>
  );
};
